name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"    # daily update
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Generate summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: MavapeGZ
          AUTO_PUSH: true
          CARD_THEME: tokyonight 
