name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"   # diario
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write   # <— NECESARIO para que AUTO_PUSH pueda commitear

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Generate summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: MavapeGZ          # <— su usuario exacto (sensible a mayúsculas)
          AUTO_PUSH: true
          # OPTIONAL: tema por defecto
          # CARD_THEME: tokyonight
